services:
  app:
    container_name: shopownerside
    build:
      context: . .
      dockerfile: ./Dockerfile
    ports:
      - "15676:15676"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres-compose-network
      - shared-network
    volumes:
      - /volumes/sos

  postgres:
    networks:
      - postgres-compose-network
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
networks:
  shared-network:
    external: true
  postgres-compose-network:
    driver: bridge