services:
  app:
    image:
      ubuntu:22.04
    build:
      context: . .
      dockerfile: ./Dockerfile
    command:
      java -jar ./swagger-spring-1.0.0.jar
    ports:
      - "15676:15676"
    volumes:
      - /usr/src/mymaven
  storage:
    image: nouchka/sqlite3
    restart: always
  companyDB:
    image: nouchka/sqlite3
    restart: always
networks:
  default:
    name: myproj_default